"""Курированные первоисточники Q2 2026 (дополняют автоматический сбор)."""

from __future__ import annotations

from tendencia.models import SourceItem

Q2_2026_SEEDS: list[SourceItem] = [
    SourceItem(
        title="MCP Security Crisis: Systemic Design (CSA)",
        url="https://labs.cloudsecurityalliance.org/wp-content/uploads/2026/05/CSA_research_note_MCP_security_crisis_20260504-csa-styled.pdf",
        published="2026-05-04",
        summary="CSA: системные риски MCP, tool poisoning, cross-server shadowing.",
        source_type="standards",
        origin="Cloud Security Alliance",
        relevance_score=1.4,
        matched_topics=["agent_tools"],
    ),
    SourceItem(
        title="MCP STDIO RCE: Supply Chain Risk (CSA)",
        url="https://labs.cloudsecurityalliance.org/wp-content/uploads/2026/05/CSA_research_note_mcp-stdio-rce-agentic-infrastructure_20260510-csa-styled.pdf",
        published="2026-05-10",
        summary="STDIO transport, CVE-2026-30623 (LiteLLM), zero-click IDE attacks.",
        source_type="gov_cert",
        origin="Cloud Security Alliance",
        relevance_score=1.45,
        matched_topics=["agent_tools"],
    ),
    SourceItem(
        title="CVE-2026-30615: Windsurf Zero-Click MCP Prompt Injection RCE",
        url="https://policylayer.com/mcp-incidents/windsurf-zero-click-mcp-rce-cve-2026-30615",
        published="2026-04-15",
        summary="OX Security advisory: prompt injection → mcp.json overwrite → RCE.",
        source_type="incidents",
        origin="PolicyLayer / OX Security",
        relevance_score=1.5,
        matched_topics=["agent_tools"],
    ),
    SourceItem(
        title="MCP Is the New Supply Chain (Lorikeet Security)",
        url="https://lorikeetsecurity.com/blog/mcp-supply-chain-attacks-ai-agent-security",
        published="2026-04-01",
        summary="30+ CVE, npm hijack WAVESHAPER, 7000+ exposed MCP servers.",
        source_type="news",
        origin="Lorikeet Security",
        relevance_score=1.35,
        matched_topics=["agent_tools"],
    ),
    SourceItem(
        title="State of MCP Security Audit — June 2026",
        url="https://policylayer.com/research/state-of-mcp",
        published="2026-06-01",
        summary="2031 MCP servers: ~40% destructive/exec tools, 96% без предупреждений.",
        source_type="papers",
        origin="PolicyLayer",
        relevance_score=1.3,
        matched_topics=["agent_tools"],
    ),
    SourceItem(
        title="Zombie Agents: Persistent Control of Self-Evolving LLM Agents",
        url="https://arxiv.org/pdf/2602.15654",
        published="2026-02-15",
        summary="Self-reinforcing memory injection, persistent cross-session control.",
        source_type="papers",
        origin="arXiv",
        relevance_score=1.4,
        matched_topics=["self_evolving_agents"],
    ),
    SourceItem(
        title="Your Agent May Misevolve (ICLR 2026)",
        url="https://openreview.net/forum?id=Fd1jgQQW28",
        published="2026-04-01",
        summary="Misevolution: деградация alignment, уязвимые tools, workflow drift.",
        source_type="papers",
        origin="ICLR 2026",
        relevance_score=1.35,
        matched_topics=["self_evolving_agents"],
    ),
    SourceItem(
        title="When AI Remembers Too Much (Unit 42)",
        url="https://unit42.paloaltonetworks.com/indirect-prompt-injection-poisons-ai-longterm-memory/",
        published="2026-05-01",
        summary="Poisoning long-term memory агентов, persistent malicious instructions.",
        source_type="vendor",
        origin="Palo Alto Unit 42",
        relevance_score=1.3,
        matched_topics=["self_evolving_agents", "prompt_injection"],
    ),
    SourceItem(
        title="AI Act: Digital Omnibus agreement (European Parliament)",
        url="https://www.europarl.europa.eu/pdfs/news/expert/2026/5/press_release/20260427IPR42011/20260427IPR42011_en.pdf",
        published="2026-05-07",
        summary="Перенос high-risk obligations до Dec 2027 / Aug 2028; упрощение compliance.",
        source_type="gov_cert",
        origin="European Parliament",
        relevance_score=1.2,
        matched_topics=["ai_regulation"],
    ),
    SourceItem(
        title="Article 15: Accuracy, Robustness and Cybersecurity (EU AI Act)",
        url="https://artificialintelligenceact.eu/article/15/",
        published="2026-04-01",
        summary="Требования к cybersecurity high-risk AI: poisoning, adversarial examples.",
        source_type="standards",
        origin="EU AI Act",
        relevance_score=1.15,
        matched_topics=["ai_regulation"],
    ),
]
